version: "3.7"

services:
  node:
    build:
      context: ../..
      dockerfile: deployment/docker-compose/Dockerfile
    working_dir: /app
    container_name: node-container
    ports:
      - 5000:5000
    env_file: 
        - ".env.${DOCKER_ENV}"
    command: >
      /bin/sh /app/init.sh
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb-container
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    env_file: 
        - ".env.${DOCKER_ENV}"
