  
version: "3"
services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongo-db-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: <username>
      MONGO_INITDB_ROOT_PASSWORD: <password>
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db